---
# This is a basic workflow to help you get started with Actions
name: Molecule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master
      - tags/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  requirements:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: tcharl.freeipa_server
      - name: install prereq
        run: |
          cd tcharl.freeipa_server
          ansible-galaxy role install -r requirements-standalone.yml
          ansible-galaxy collection install -r requirements-collections.yml
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: tcharl.freeipa_server
      - name: update apt
        run: |
          sudo apt update
      - name: install aptitude packages
        run: |
          sudo apt -y install sudo python3 python3-pip
      - name: pip install packages
        run: |
          pip3 install wheel setuptools tox
      - name: tox lint
        run: |
          cd tcharl.freeipa_server
          tox -e lint
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: tcharl.freeipa_server
      - name: update apt
        run: |
          sudo apt update
#      - name: apt upgrade
#        run: |
#          sudo apt upgrade
      - name: install aptitude packages
        run: |
          sudo apt -y install sudo python3 python3-pip podman
      - name: pip install packages
        run: |
          pip3 install wheel setuptools tox
      - name: Test with podman
        run: |
          cd tcharl.freeipa_server
          tox -e test-exec